### ISSUE TITLE
create complex array

### ISSUE THREAD

**Issue by drom** [indutny/fft.js#5]
I have trouble finding public API for creating complex array filling `Real` and `Imaginary` parts.
`f.toComplexArray(input, arr)`  seems to take real `input` array as argument.
Do I miss something?

**Comment by indutny** [comment]
The structure of array is pretty easy:

`[re0, im0, re1, im1, ... ]`

`toComplexArray` is just a helper method that takes an array of real values of size `fft.size` and outputs `[re0, 0, re1, 0, ... ]`. Second argument may be used for caching the result, if it is provided - the data will be filled into it instead of creating new array.

**Comment by drom** [comment]
yep, make sense.

**Comment by indutny** [comment]
Added API Details to readme: https://github.com/indutny/fft.js#api-details
